EC\easyCloudBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: EC\easyCloudBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pseudo:
            type: string
            length: '30'
            unique: true
        pass:
            type: string
            length: '30'
        mail:
            type: string
            length: '100'
            unique: true
        derniereCo:
            type: date
    lifecycleCallbacks: {  }
