e_ceasy_cloud_default:
    path:     /
    defaults: { _controller: ECeasyCloudBundle:Default:index }

e_ceasy_cloud_inscription:
   path:     /inscription
   defaults: { _controller: ECeasyCloudBundle:inscription:index }
   methods:   [GET]


e_ceasy_cloud_inscriptionPost:
   path:     /inscription
   defaults: { _controller: ECeasyCloudBundle:User:ajoutUtilisateur }
   methods:   [POST]

e_ceasy_cloud_authentification:
   path:     /authentification
   defaults: { _controller: ECeasyCloudBundle:User:authentificationUtilisateur }
   methods:   [POST]

e_ceasy_cloud_repertoire:
   path:     /repertoire
   defaults: { _controller: ECeasyCloudBundle:Repertoire:afficherRepertoire }
   methods:   [GET]

e_ceasy_cloud_telecharger:
   path:     /telecharger/{fichier}
   defaults: { _controller: ECeasyCloudBundle:Repertoire:telechargerFichier }
   methods:   [GET]

e_ceasy_cloud_upload:
   path:     /upload
   defaults: { _controller: ECeasyCloudBundle:Repertoire:televerserFichier }
   methods:   [POST]

e_ceasy_cloud_supprimer:
   path:     /supprimer/{fichier}
   defaults: { _controller: ECeasyCloudBundle:Repertoire:supprimerFichier }
   methods:   [GET]

e_ceasy_cloud_deco:
   path:     /deconnexion
   defaults: { _controller: ECeasyCloudBundle:User:deconnexion }
   methods:   [GET]
