e_ceasy_cloud_default:
    path:     /
    defaults: { _controller: ECeasyCloudBundle:Default:index }

e_ceasy_cloud_inscription:
   path:     /inscription
   defaults: { _controller: ECeasyCloudBundle:inscription:index }
   methods:   [GET]


e_ceasy_cloud_inscriptionPost:
   path:     /inscription
   defaults: { _controller: ECeasyCloudBundle:User:AjoutUtilisateur }
   methods:   [POST]


e_ceasy_cloud_accueilPost:
   path:     /authentication
   defaults: { _controller: ECeasyCloudBundle:User:AuthentificationAction}
   methods:   [POST]
   
