<?php

namespace EC\easyCloudBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 use Doctrine\ORM\EntityRepository;

 class UserRepository extends EntityRepository
 {
   public function findByPseudoAndPass($pseudo, $pass)
   {
     $qb = $this->createQueryBuilder('a');

      $qb->where('a.pseudo = :pseudo')
           ->setParameter('pseudo', $pseudo)
         ->andWhere('a.pass < :pass')
           ->setParameter('pass', $pass)
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
   }
}
